language: python
group: travis_latest
dist: xenial

services: xvfb

git:
  depth: 3
  quiet: true

matrix:
  include:
  - os: linux
    python: 3.7
    install: pip install -e .[tests,cov]
    script: 
    - flake8
    - mypy . --ignore-missing-imports
    after_success:
    - pytest --cov
    - coveralls
  - os: osx
    language: sh
    install: pip3 install -e .[tests]
  - os: windows
    language: sh
    before_install:
    - choco install python3
    - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
    
install: pip install -e .[tests]

script: pytest -rsv

